version: 2
updates:
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "dyamada-jaki"
    assignees:
      - "dyamada-jaki"
    commit-message:
      prefix: "🔧"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "@google/generative-ai"
        update-types: ["version-update:semver-major"]
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "dyamada-jaki"
    assignees:
      - "dyamada-jaki"
    commit-message:
      prefix: "🚀"
      include: "scope"
    labels:
      - "dependencies"
      - "ci/cd"
